### ISSUE TITLE
“TypeError: Descriptors cannot not be created directly”

### ISSUE THREAD

**Issue by mdabir1203** [42Berlin/42Berlin_AI#2]
##Cause of Error: 
occurs because of incompatibility of protobuf package. [This incompatibility can be direct or because of any other python module](https://www.datasciencelearner.com/typeerror-descriptors-cannot-not-be-created-directly-solved/)[1](https://www.datasciencelearner.com/typeerror-descriptors-cannot-not-be-created-directly-solved/)

##Fix
`pip install protobuf==3.20.0`
Incase of wsl this is a safe choice to do -> exporting the env 
´export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`

**Comment by HasanOmeis** [comment]
fix didnt work why?

**Comment by mdabir1203** [comment]
did you install the actual version. What is the error shown ?

**Comment by HasanOmeis** [comment]
error shown while importing tensorflow it says i should down grade protobuf, after downgrading another error show that says tensorflow 2 needs protobuf version 4 and above 🙄

**Comment by mdabir1203** [comment]
downgrade the tensorflow version then 👍🏾

**Comment by mdabir1203** [comment]
Also do you use a virtualenv to work on ?
